Exit `screenshot` when xclip isn't found
Due to an oversight, the OR operator was used instead of the AND
operator, making it possible to run the script even when `import` is
present but `xclip` isn't.

diff --git a/bin/screenshot b/bin/screenshot
--- a/bin/screenshot
+++ b/bin/screenshot
@@ -27,9 +27,9 @@ ss() {
 			    "Screenshot saved" "$file_name"
 }
 
-if ! (command -v import || command -v xclip) > /dev/null
+if ! (command -v import && command -v xclip) > /dev/null
 then
-	>&2 echo "Error: This script requires imagemagik and xclip.\n"
+	>&2 printf "Error: This script requires imagemagik and xclip.\n"
 	exit 1
 fi
 
